import json
import os

def update_notebook(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # 1. Update infer_perch_batch (Cell 6)
    for cell in nb['cells']:
        if cell['cell_type'] == 'code' and 'def infer_perch_batch' in ''.join(cell['source']):
            cell['source'] = [
                'from concurrent.futures import ThreadPoolExecutor\n',
                '\n',
                'def read_soundscape_60s(path):\n',
                '    """Load a 60-second soundscape, padding or truncating to exact length."""\n',
                '    y, sr = sf.read(path, dtype="float32", always_2d=False)\n',
                '    if y.ndim == 2:\n',
                '        y = y.mean(axis=1)\n',
                '    if len(y) < CFG.FILE_SAMPLES:\n',
                '        y = np.pad(y, (0, CFG.FILE_SAMPLES - len(y)))\n',
                '    return y[:CFG.FILE_SAMPLES]\n',
                '\n',
                '\n',
                'def infer_perch_batch(paths, verbose=True):\n',
                '    """Run Perch v2 on a list of soundscape paths with threaded audio loading.\n',
                '    Returns metadata DataFrame, raw score matrix, and embedding matrix."""\n',
                '    paths   = [Path(p) for p in paths]\n',
                '    n_rows  = len(paths) * CFG.N_WINDOWS\n',
                '    row_ids    = np.empty(n_rows, dtype=object)\n',
                '    filenames  = np.empty(n_rows, dtype=object)\n',
                '    sites      = np.empty(n_rows, dtype=object)\n',
                '    hours      = np.empty(n_rows, dtype=np.int16)\n',
                '    scores     = np.zeros((n_rows, N_CLASSES), dtype=np.float32)\n',
                '    embeddings = np.zeros((n_rows, 1536),      dtype=np.float32)\n',
                '    write_row = 0\n',
                '    \n',
                '    # Process files in larger batches to maximize CPU throughput\n',
                '    batch_size = CFG.BATCH_FILES\n',
                '    with ThreadPoolExecutor(max_workers=4) as executor:\n',
                '        itr = tqdm(range(0, len(paths), batch_size), desc="Perch Inference", disable=not verbose)\n',
                '        for start in itr:\n',
                '            batch_paths = paths[start : start + batch_size]\n',
                '            \n',
                '            # Threaded audio loading while CPU-based Perch might be active\n',
                '            batch_audio = list(executor.map(read_soundscape_60s, batch_paths))\n',
                '            x_batch = np.array(batch_audio, dtype=np.float32).reshape(-1, CFG.WINDOW_SAMPLES)\n',
                '            \n',
                '            bstart = write_row\n',
                '            for bi, path in enumerate(batch_paths):\n',
                '                meta = parse_soundscape_filename(path.name)\n',
                '                row_ids[write_row : write_row + CFG.N_WINDOWS] = [f"{path.stem}_{t}" for t in range(5, 65, 5)]\n',
                '                filenames[write_row : write_row + CFG.N_WINDOWS] = path.name\n',
                '                sites[write_row : write_row + CFG.N_WINDOWS]     = meta["site"]\n',
                '                hours[write_row : write_row + CFG.N_WINDOWS]     = meta["hour_utc"]\n',
                '                write_row += CFG.N_WINDOWS\n',
                '                \n',
                '            out    = infer_fn(inputs=tf.convert_to_tensor(x_batch))\n',
                '            logits = out["label"].numpy().astype(np.float32)\n',
                '            emb    = out["embedding"].numpy().astype(np.float32)\n',
                '            \n',
                '            # Map Perch logits to competition species\n',
                '            scores[bstart:write_row, MAPPED_POS] = logits[:, MAPPED_BC_INDICES]\n',
                '            embeddings[bstart:write_row] = emb\n',
                '            \n',
                '            # Apply genus-level proxy max-pooling\n',
                '            for pos, bc_idx_arr in selected_proxy_pos_to_bc.items():\n',
                '                scores[bstart:write_row, pos] = logits[:, bc_idx_arr].max(axis=1)\n',
                '                \n',
                '            del x_batch, batch_audio, out, logits, emb\n',
                '            import gc; gc.collect()\n',
                '            \n',
                '    meta_df = pd.DataFrame({"row_id": row_ids, "filename": filenames, "site": sites, "hour_utc": hours})\n',
                '    return meta_df, scores, embeddings\n'
            ]

    # 2. Update build_class_features (Cell 9)
    for cell in nb['cells']:
        if cell['cell_type'] == 'code' and 'def seq_features_1d' in ''.join(cell['source']):
            cell['source'] = [
                'def build_global_context_features(scores_matrix):\n',
                '    """\n',
                '    Vectorized computation of temporal neighbor and file-level statistics.\n',
                '    Instead of per-class loops, this calculates means, maxes, and diffs along \n',
                '    the temporal axes (N_FILES, N_WINDOWS) in one pass for all classes.\n',
                '    """\n',
                '    n_rows, n_classes = scores_matrix.shape\n',
                '    n_files = n_rows // CFG.N_WINDOWS\n',
                '    \n',
                '    # Reshape to 3D: [N_FILES, N_WINDOWS, N_CLASSES]\n',
                '    x_3d = scores_matrix.reshape(n_files, CFG.N_WINDOWS, n_classes)\n',
                '    \n',
                '    # Efficient neighborhood slicing\n',
                '    prev_x = np.concatenate([x_3d[:, :1, :], x_3d[:, :-1, :]], axis=1)\n',
                '    next_x = np.concatenate([x_3d[:, 1:, :], x_3d[:, -1:, :]], axis=1)\n',
                '    \n',
                '    # File-level aggregate statistics\n',
                '    mean_x = np.repeat(x_3d.mean(axis=1, keepdims=True), CFG.N_WINDOWS, axis=1)\n',
                '    max_x  = np.repeat(x_3d.max(axis=1, keepdims=True), CFG.N_WINDOWS, axis=1)\n',
                '    std_x  = np.repeat(x_3d.std(axis=1, keepdims=True), CFG.N_WINDOWS, axis=1)\n',
                '    \n',
                '    # Calculate differentials\n',
                '    diff_mean = x_3d - mean_x\n',
                '    diff_prev = x_3d - prev_x\n',
                '    diff_next = x_3d - next_x\n',
                '    \n',
                '    return {\n',
                '        "prev": prev_x.reshape(n_rows, n_classes),\n',
                '        "next": next_x.reshape(n_rows, n_classes),\n',
                '        "mean": mean_x.reshape(n_rows, n_classes),\n',
                '        "max":  max_x.reshape(n_rows, n_classes),\n',
                '        "std":  std_x.reshape(n_rows, n_classes),\n',
                '        "diff_mean": diff_mean.reshape(n_rows, n_classes),\n',
                '        "diff_prev": diff_prev.reshape(n_rows, n_classes),\n',
                '        "diff_next": diff_next.reshape(n_rows, n_classes)\n',
                '    }\n',
                '\n',
                'def build_class_features_optimized(Z, cls_idx, raw_all, prior_all, base_all, context_dict):\n',
                '    """Assembles the feature vector for a specific species classifier using pre-computed context."""\n',
                '    raw_col   = raw_all[:, cls_idx, None]\n',
                '    prior_col = prior_all[:, cls_idx, None]\n',
                '    base_col  = base_all[:, cls_idx, None]\n',
                '    \n',
                '    # Extract pre-computed context for THIS class\n',
                '    prev_base = context_dict["prev"][:, cls_idx, None]\n',
                '    next_base = context_dict["next"][:, cls_idx, None]\n',
                '    mean_base = context_dict["mean"][:, cls_idx, None]\n',
                '    max_base  = context_dict["max"][:, cls_idx, None]\n',
                '    std_base  = context_dict["std"][:, cls_idx, None]\n',
                '    diff_mean = context_dict["diff_mean"][:, cls_idx, None]\n',
                '    diff_prev = context_dict["diff_prev"][:, cls_idx, None]\n',
                '    diff_next = context_dict["diff_next"][:, cls_idx, None]\n',
                '    \n',
                '    return np.concatenate([\n',
                '        Z, raw_col, prior_col, base_col,\n',
                '        prev_base, next_base, mean_base, max_base, std_base,\n',
                '        diff_mean, diff_prev, diff_next,\n',
                '        (raw_col * prior_col), (raw_col * base_col), (prior_col * base_col)\n',
                '    ], axis=1).astype(np.float32)\n'
            ]

    # 3. Update Probe application logic (Cell 10)
    for cell in nb['cells']:
        if cell['cell_type'] == 'code' and 'emb_pca.transform(emb_test_scaled)' in ''.join(cell['source']):
            cell['source'] = [
                '# vectorized Bayesian fusion built on provided labeled data\n',
                'final_tables = fit_prior_tables(sc_clean.reset_index(drop=True), Y_SC)\n',
                'scores_test_fused, prior_test = fuse_scores(\n',
                '    scores_test_raw, sites=meta_test["site"].to_numpy(),\n',
                '    hours=meta_test["hour_utc"].to_numpy(), tables=final_tables)\n',
                '\n',
                '# --- Optimized Metadata-Probe Application ---\n',
                '# 1. Scale and project latent embeddings\n',
                'emb_test_scaled = emb_scaler.transform(emb_test)\n',
                'Z_test = emb_pca.transform(emb_test_scaled).astype(np.float32)\n',
                'scores_final = scores_test_fused.copy()\n',
                '\n',
                '# 2. Vectorized calculation of file-level context features (once for all 234 classes)\n',
                'print("Building global context features for metadata probes...")\n',
                'context_test = build_global_context_features(scores_test_fused)\n',
                '\n',
                '# 3. Serial execution of frozen classifiers with pre-computed features\n',
                'for cls_idx, clf in tqdm(probe_models.items(), desc="Applying Probes"):\n',
                '    X_test_cls = build_class_features_optimized(\n',
                '        Z_test, cls_idx, scores_test_raw, prior_test, scores_test_fused, context_test)\n',
                '    \n',
                '    # Probe probability blending logic\n',
                '    pred_prob = clf.predict_proba(X_test_cls)[:, 1].astype(np.float32)\n',
                '    pred_logit = np.log(pred_prob + 1e-7) - np.log(1 - pred_prob + 1e-7)\n',
                '    scores_final[:, cls_idx] = (1.0 - CFG.PROBE_ALPHA) * scores_test_fused[:, cls_idx] + CFG.PROBE_ALPHA * pred_logit\n',
                '\n',
                'print(f"Expert Probes applied to {len(probe_models)} species hierarchies.")\n'
            ]

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)

if __name__ == "__main__":
    update_notebook("BirdCLEF+ 2026/birdclef-2026-perch-v2-bayesian-fusion.ipynb")
